import prem1 from "../../../assets/prem1.jpeg";
import prem2 from "../../../assets/prem2.jpeg";
import prem3 from "../../../assets/prem3.jpeg";
import prem4 from "../../../assets/prem4.jpeg";
import prem5 from "../../../assets/prem5.jpeg";
import prem6 from "../../../assets/prem6.jpeg";
import prem7 from "../../../assets/prem7.jpeg";
import prem8 from "../../../assets/prem8.jpeg";
import prem9 from "../../../assets/prem9.jpeg";
import prem11 from "../../../assets/prem11.jpeg";
import prem12 from "../../../assets/prem12.jpeg";
import prem13 from "../../../assets/prem13.jpeg";
import pr1 from "../../../assets/pr1.jpeg";
import pr2 from "../../../assets/pr2.jpeg";
import pr3 from "../../../assets/pr3.jpeg";
import pr4 from "../../../assets/pr4.jpeg";
import pr5 from "../../../assets/pr5.jpeg";
import pr6 from "../../../assets/pr6.jpeg";
import pr7 from "../../../assets/pr7.jpeg";
import pr8 from "../../../assets/pr8.jpeg";
import pr9 from "../../../assets/pr9.jpeg";
import pr11 from "../../../assets/pr11.jpeg";
import pr12 from "../../../assets/pr12.jpeg";
import pr13 from "../../../assets/pr13.jpeg";
import prod1 from "../../../assets/prod1.jpeg";
import prod2 from "../../../assets/prod2.jpeg";
import prod3 from "../../../assets/prod3.jpeg";
import prod4 from "../../../assets/prod4.jpeg";


export const boutiqueList = [
  {
    id: 11,
    img: prem11,
    title: "Trendy Fits To Keep You Fit | 4 - 14Y",
    details: "",
    buttonTitle: "Boutique ends in 6 days  & 7 hours",
    productDetails: {
      productBackground: pr11,
      productList: [
        {
            id: Math.floor(Math.random() * 10000),
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            id:Math.floor(Math.random() * 1000),
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
        id:Math.floor(Math.random() * 10),
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            id:Math.floor(Math.random() * 10000),
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            id:Math.floor(Math.random() * 1000),
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 10000),
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 10000),
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 10000),
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 10000),
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 10000),
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 10000),
            img: prod3,
            productName:"Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            id:Math.floor(Math.random() * 100),
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 12,
    img: prem12,
    title: "Cute & Comfy Corner For Babies",
    details: "Onesies and Rompers",
    buttonTitle: "Boutique ends in 6 days  & 7 hours",
    productDetails: {
      productBackground: pr12,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 13,
    img: prem13,
    title: "Go Googly Eyed | Up to 14Y",
    details: "Character Merch For Your Fanboy/Fangirl",
    buttonTitle: "Boutique ends in 6 days  & 7 hours",
    productDetails: {
      productBackground: pr13,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 1,
    img: prem1,
    title: "Safety first",
    details: "Face masks, sanitizers, safety ",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 2,
    img: prem2,
    title: "Fab & Unique Choices | 2 - 14",
    details: "Tops, Tees, Bottoms, & more",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 3,
    img: prem3,
    title: "Shoe Stores To Step Into | Up to 14Y",
    details: "Athleisure & Footwear",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 4,
    img: prem4,
    title: "Safety first",
    details: "Face masks, sanitizers, safety ",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 5,
    img: prem5,
    title: "Fab & Unique Choices | 2 - 14",
    details: "Tops, Tees, Bottoms, & more",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 6,
    img: prem6,
    title: "Shoe Stores To Step Into | Up to 14Y",
    details: "Athleisure & Footwear",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 7,
    img: prem7,
    title: "Safety first",
    details: "Face masks, sanitizers, safety ",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 8,
    img: prem8,
    title: "Fab & Unique Choices | 2 - 14",
    details: "Tops, Tees, Bottoms, & more",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
  {
    id: 9,
    img: prem9,
    title: "Shoe Stores To Step Into | Up to 14Y",
    details: "Athleisure & Footwear",
    buttonTitle: "Boutique ends in 6 days  & 7 hours ",
    productDetails: {
      productBackground: pr1,
      productList: [
        {
          img: prod1,
          productName: "Pine ActiveAthleisure &... ",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod2,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod3,
          productName:
            "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
          img: prod4,
          productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
          summary: "Multiple Sizes Available",
          oldPrice: "849",
          newPrice: "619.77",
          clubPrice: "6117",
          date: "Thursday, May 11",
        },
        {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod1,
            productName: "Pine ActiveAthleisure &... ",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod2,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod3,
            productName:
              "Pine Active Half Sleeves Quick Dry T-shirt with HD Print - Aqua Blu",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
          {
            img: prod4,
            productName: "Pine Active Half Sleeves T-shirt with HD Print - Green",
            summary: "Multiple Sizes Available",
            oldPrice: "849",
            newPrice: "619.77",
            clubPrice: "6117",
            date: "Thursday, May 11",
          },
      ],
    },
  },
];
